name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Authenticate to GCP (Fake)
        run: echo "Fake authentication succeeded"

      - name: Setup gcloud (Fake)
        run: echo "Fake gcloud setup done"

      - name: Build and push Docker image (Fake)
        run: echo "Docker image pushed successfully"
